<?php

namespace App\Services;

use App\Models\Booking;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Log;
use Exception;

class PDFService
{
    /**
     * Generate booking invoice PDF
     *
     * FIX: Replaced Pdf::loadView() with a two-step approach:
     *  1. Render Blade template to an HTML string.
     *  2. Rewrite all HTTP asset() URLs → file:// local paths.
     *  3. Load the sanitised HTML into DomPDF with isRemoteEnabled = false.
     *
     * WHY: DomPDF's Helpers::build_url() (line 1136) was attempting to
     * fetch every asset() URL (logo, images) via a live HTTP request.
     * In local/dev environments those requests loop back to the same PHP
     * process and block until max_execution_time is exceeded, producing:
     *   "Fatal error: Maximum execution time of 30+2 seconds exceeded
     *    in dompdf/src/Helpers.php on line 1136"
     *
     * Setting isRemoteEnabled = false alone stops the hang but also
     * silently drops images. Rewriting to file:// paths first ensures
     * images still render correctly from the local public/ directory.
     *
     * @param Booking $booking
     * @return string  Storage path to the generated PDF
     * @throws \Exception
     */
    public function generateBookingInvoice(Booking $booking): string
    {
        try {
            // ----------------------------------------------------------------
            // 1. Eager-load all relationships the template needs.
            //    Avoids N+1 queries and ensures data is available.
            // ----------------------------------------------------------------
            $booking->load(['hall.owner', 'extraServices']);

            Log::info('Starting invoice generation', ['booking_id' => $booking->id]);

            // ----------------------------------------------------------------
            // 2. Render the Blade view to a raw HTML string.
            //    We do NOT pass it to DomPDF yet — we pre-process it first.
            // ----------------------------------------------------------------
            $html = view('pdf.invoice', [
                'booking'       => $booking,
                'hall'          => $booking->hall,
                'owner'         => $booking->hall->owner,
                'extraServices' => $booking->extraServices,
            ])->render();

            // ----------------------------------------------------------------
            // 3. KEY FIX: Replace every HTTP/HTTPS asset URL that points to
            //    this application (generated by asset() or url()) with its
            //    equivalent file:// path inside public/.
            //
            //    DomPDF respects file:// URIs without making any network call,
            //    so this completely eliminates the HTTP-request hang.
            //
            //    Pattern matches the full app URL prefix and captures the
            //    remainder (e.g. "images/logo.webp").
            // ----------------------------------------------------------------
            $appUrl  = rtrim(config('app.url'), '/');
            $pubPath = rtrim(public_path(), '/');

            $html = preg_replace_callback(
                // Match src="http://..." and href="http://..." for app assets
                '/(src|href)=["\']' . preg_quote($appUrl, '/') . '\/([^"\'> ]*)["\']/',
                static function (array $m) use ($pubPath): string {
                    // Convert to a file:// URI DomPDF can read locally
                    $localPath = $pubPath . '/' . ltrim($m[2], '/');
                    return $m[1] . '="file://' . $localPath . '"';
                },
                $html
            );

            // ----------------------------------------------------------------
            // 4. Load the pre-processed HTML into DomPDF and configure it
            //    to use local files only (no outbound HTTP whatsoever).
            // ----------------------------------------------------------------
            $pdf = Pdf::loadHTML($html);

            $dompdf = $pdf->getDomPDF();

            // Disable remote HTTP fetching — the primary fix for the timeout.
            $dompdf->set_option('isRemoteEnabled', false);

            // Allow DomPDF to read files from the public/ directory tree.
            $dompdf->set_option('chroot', public_path());

            // Standard rendering options.
            $dompdf->set_option('isHtml5ParserEnabled', true);
            $dompdf->set_option('isFontSubsettingEnabled', true);
            $dompdf->set_option('defaultFont', 'DejaVu Sans');

            $pdf->setPaper('a4', 'portrait');

            // ----------------------------------------------------------------
            // 5. Build the storage path and persist the PDF.
            // ----------------------------------------------------------------
            $filename = 'invoices/' . $booking->booking_number . '.pdf';

            // Ensure the invoices/ directory exists on the local disk.
            Storage::disk('local')->makeDirectory('invoices');

            // Write PDF bytes to storage.
            Storage::disk('local')->put($filename, $pdf->output());

            // Verify the file was actually written.
            if (! Storage::disk('local')->exists($filename)) {
                throw new \Exception('PDF file was not created on disk.');
            }

            // ----------------------------------------------------------------
            // 6. Persist the path on the booking record and confirm it saved.
            // ----------------------------------------------------------------
            $booking->update(['invoice_path' => $filename]);

            $booking->refresh();

            if (empty($booking->invoice_path)) {
                throw new \Exception('Invoice path was not saved to the database.');
            }

            Log::info('Invoice generated successfully', [
                'booking_id' => $booking->id,
                'filename'   => $filename,
                'file_size'  => Storage::disk('local')->size($filename),
            ]);

            return $filename;

        } catch (\Exception $e) {
            Log::error('Invoice generation failed', [
                'booking_id' => $booking->id,
                'error'      => $e->getMessage(),
                'trace'      => $e->getTraceAsString(),
            ]);

            throw $e;
        }
    }

    /**
     * Generate booking confirmation PDF
     */
    public function generateBookingConfirmation(Booking $booking): string
    {
        try {
            $pdf = Pdf::loadView('pdf.confirmation', [
                'booking' => $booking,
                'hall'    => $booking->hall,
                'qrCode'  => $this->generateQRCode($booking),
            ]);

            $filename = 'confirmations/' . $booking->booking_number . '.pdf';

            Storage::put($filename, $pdf->output());

            Log::info('Confirmation generated', ['booking_id' => $booking->id]);

            return $filename;
        } catch (Exception $e) {
            Log::error('Confirmation generation failed', [
                'booking_id' => $booking->id,
                'error'      => $e->getMessage(),
            ]);
            throw $e;
        }
    }

    /**
     * Generate owner payout report
     */
    public function generateOwnerPayoutReport(int $ownerId, string $startDate, string $endDate): string
    {
        try {
            $bookings = Booking::whereHas('hall', function ($q) use ($ownerId) {
                $q->where('owner_id', $ownerId);
            })
                ->whereIn('status', ['confirmed', 'completed'])
                ->where('payment_status', 'paid')
                ->whereBetween('booking_date', [$startDate, $endDate])
                ->with(['hall', 'extraServices'])
                ->get();

            $totalRevenue    = $bookings->sum('total_amount');
            $totalCommission = $bookings->sum('commission_amount');
            $totalPayout     = $bookings->sum('owner_payout');

            $pdf = Pdf::loadView('pdf.payout-report', [
                'bookings'        => $bookings,
                'owner'           => $bookings->first()?->hall->owner,
                'startDate'       => $startDate,
                'endDate'         => $endDate,
                'totalRevenue'    => $totalRevenue,
                'totalCommission' => $totalCommission,
                'totalPayout'     => $totalPayout,
            ]);

            $filename = 'reports/payout-' . $ownerId . '-' . date('Y-m-d') . '.pdf';

            Storage::put($filename, $pdf->output());

            Log::info('Payout report generated', ['owner_id' => $ownerId]);

            return $filename;
        } catch (Exception $e) {
            Log::error('Payout report generation failed', [
                'owner_id' => $ownerId,
                'error'    => $e->getMessage(),
            ]);
            throw $e;
        }
    }

    /**
     * Generate monthly revenue report
     */
    public function generateMonthlyRevenueReport(int $month, int $year): string
    {
        try {
            $startDate = "$year-$month-01";
            $endDate   = date('Y-m-t', strtotime($startDate));

            $bookings = Booking::whereIn('status', ['confirmed', 'completed'])
                ->where('payment_status', 'paid')
                ->whereBetween('booking_date', [$startDate, $endDate])
                ->with(['hall', 'user'])
                ->get();

            $stats = [
                'total_bookings'    => $bookings->count(),
                'total_revenue'     => $bookings->sum('total_amount'),
                'total_commission'  => $bookings->sum('commission_amount'),
                'total_owner_payout'=> $bookings->sum('owner_payout'),
                'by_hall'           => $bookings->groupBy('hall_id')->map(function ($hallBookings) {
                    return [
                        'hall'    => $hallBookings->first()->hall,
                        'count'   => $hallBookings->count(),
                        'revenue' => $hallBookings->sum('total_amount'),
                    ];
                }),
            ];

            $pdf = Pdf::loadView('pdf.monthly-report', [
                'bookings' => $bookings,
                'stats'    => $stats,
                'month'    => $month,
                'year'     => $year,
            ]);

            $filename = "reports/monthly-$year-$month.pdf";

            Storage::put($filename, $pdf->output());

            Log::info('Monthly report generated', ['month' => $month, 'year' => $year]);

            return $filename;
        } catch (Exception $e) {
            Log::error('Monthly report generation failed', ['error' => $e->getMessage()]);
            throw $e;
        }
    }

    /**
     * Generate QR code for booking
     */
    protected function generateQRCode(Booking $booking): string
    {
        // You can use libraries like SimpleSoftwareIO/simple-qrcode
        // For now, return a placeholder
        return "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==";
    }

    /**
     * Get PDF from storage
     */
    public function getPDF(string $path): ?string
    {
        if (Storage::exists($path)) {
            return Storage::path($path);
        }

        return null;
    }

    /**
     * Download PDF
     */
    public function downloadPDF(string $path, string $filename = 'document.pdf')
    {
        if (Storage::exists($path)) {
            return Storage::download($path, $filename);
        }

        abort(404, 'PDF not found');
    }

    /**
     * Delete PDF
     */
    public function deletePDF(string $path): bool
    {
        if (Storage::exists($path)) {
            return Storage::delete($path);
        }

        return false;
    }

    /**
     * Generate payment receipt PDF
     *
     * @param \App\Models\Payment $payment
     * @return string Filename of generated PDF
     */
    public function generatePaymentReceipt(\App\Models\Payment $payment): string
    {
        // Load relationships
        $payment->load('booking.hall');

        // Generate filename
        $filename  = 'receipt_' . $payment->payment_reference . '_' . now()->format('YmdHis') . '.pdf';
        $directory = 'receipts';
        $path      = $directory . '/' . $filename;

        // Ensure directory exists
        if (! Storage::disk('local')->exists($directory)) {
            Storage::disk('local')->makeDirectory($directory);
        }

        // Generate PDF
        $pdf = \Barryvdh\DomPDF\Facade\Pdf::loadView('pdf.payment-receipt', [
            'payment' => $payment,
            'booking' => $payment->booking,
            'hall'    => $payment->booking?->hall,
        ]);

        // Save PDF
        Storage::disk('local')->put($path, $pdf->output());

        return $filename;
    }
}
