<?php

declare(strict_types=1);

namespace App\Filament\Owner\Resources\HallResource\Pages;

use App\Filament\Owner\Resources\HallResource;
use Filament\Resources\Pages\CreateRecord;
use Filament\Notifications\Notification;
use Illuminate\Support\Facades\Auth;

/**
 * CreateHall Page for Owner Panel
 *
 * Handles hall creation with automatic owner assignment.
 */
class CreateHall extends CreateRecord
{
    /**
     * The resource this page belongs to.
     *
     * @var string
     */
    protected static string $resource = HallResource::class;

    /**
     * Get the page title.
     */
    public function getTitle(): string
    {
        return __('owner.halls.create.title');
    }

    /**
     * Mutate form data before creating the record.
     *
     * @param array<string, mixed> $data
     * @return array<string, mixed>
     */
    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $user = Auth::user();

        // Automatically assign the hall to the current owner
        $data['owner_id'] = $user->id;

        // Set default values if not provided
        $data['is_active'] = $data['is_active'] ?? true;
        $data['is_featured'] = false; // Only admins can feature halls
        $data['requires_approval'] = $data['requires_approval'] ?? false;

        // Ensure features is an array
        if (isset($data['features']) && is_array($data['features'])) {
            $data['features'] = array_values(array_filter($data['features']));
        } else {
            $data['features'] = [];
        }

        return $data;
    }

    /**
     * Handle actions after the record is created.
     *
     * Note: Availability is automatically generated by the Hall model's created event.
     * No need to call generateAvailability() here.
     */
    protected function afterCreate(): void
    {
        // Availability is auto-generated by Hall model's created event
        // No additional action needed here
    }

    /**
     * Get the redirect URL after creating the record.
     */
    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('edit', ['record' => $this->record]);
    }

    /**
     * Get the created notification.
     */
    protected function getCreatedNotification(): ?Notification
    {
        return Notification::make()
            ->success()
            ->title(__('owner.halls.notifications.created'))
            ->body(__('owner.halls.notifications.availability_generated'));
    }
}
