<?php

declare(strict_types=1);

namespace App\Notifications;

use App\Models\Booking;
use App\Services\BookingPdfService;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

/**
 * Customer Booking Confirmation Notification
 *
 * Sends booking confirmation email to REGISTERED customers after successful payment.
 * Includes booking details, payment summary, and PDF confirmation as attachment.
 *
 * This mirrors the guest flow's GuestBookingConfirmationNotification but:
 * - Uses customer dashboard URL instead of guest_token URL
 * - Attaches the booking PDF generated by BookingPdfService
 * - Supports both full and advance (partial) payment info
 * - Bilingual support (English/Arabic)
 *
 * Reuses existing infrastructure:
 * - BookingPdfService::generateConfirmation() for PDF generation
 * - Existing translation keys from emails.php and halls.php
 *
 * @package App\Notifications
 * @version 1.0.0
 */
class CustomerBookingConfirmationNotification extends Notification implements ShouldQueue
{
    use Queueable;

    /**
     * The confirmed booking instance.
     *
     * @var Booking
     */
    protected Booking $booking;

    /**
     * Create a new notification instance.
     *
     * @param Booking $booking The confirmed booking with payment completed
     */
    public function __construct(Booking $booking)
    {
        $this->booking = $booking;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param mixed $notifiable
     * @return array<int, string>
     */
    public function via(mixed $notifiable): array
    {
        return ['mail'];
    }

    /**
     * Get the mail representation of the notification.
     *
     * Builds a rich confirmation email with:
     * - Booking details (hall, date, time slot, guests)
     * - Payment summary (amount paid, advance/full, balance due)
     * - PDF attachment (booking confirmation)
     * - CTA button to view booking in customer dashboard
     *
     * @param mixed $notifiable
     * @return MailMessage
     */
    public function toMail(mixed $notifiable): MailMessage
    {
        $locale = app()->getLocale();
        $booking = $this->booking;

        // Load relationships if not already loaded
        $booking->loadMissing(['hall.city.region', 'extraServices', 'user']);

        // Get localized hall name (handles Spatie Translatable JSON or plain string)
        $hallName = $this->getHallName($booking, $locale);

        // Get localized city name
        $cityName = $this->getCityName($booking, $locale);

        // Format time slot for display
        $timeSlot = $this->getTimeSlotLabel($booking->time_slot);

        // Build the customer dashboard booking URL
        $bookingUrl = route('customer.booking.details', ['booking' => $booking->id]);

        // Determine payment display info (full vs advance)
        $isAdvance = $booking->isAdvancePayment();
        $amountPaid = $isAdvance
            ? number_format((float) $booking->advance_amount, 3)
            : number_format((float) $booking->total_amount, 3);
        $paymentLabel = $isAdvance
            ? __('emails.booking.advance_payment', [], 'Advance Payment')
            : __('emails.booking.payment_complete', [], 'Payment Complete');

        // Build the email message
        $mail = (new MailMessage())
            ->subject(__('emails.booking.confirmed.subject', [
                'booking_number' => $booking->booking_number,
            ], 'Booking Confirmed - ' . $booking->booking_number))
            ->greeting(__('emails.booking.greeting', [
                'name' => $booking->customer_name,
            ], 'Dear ' . $booking->customer_name . ','))
            ->line(__('emails.booking.confirmed.intro', [], 'Your booking has been confirmed! Here are the details:'))
            ->line('---')
            ->line("**" . __('emails.booking.booking_number', [], 'Booking Number') . ":** {$booking->booking_number}")
            ->line("**" . __('emails.booking.hall', [], 'Hall') . ":** {$hallName}")
            ->line("**" . __('emails.booking.location', [], 'Location') . ":** {$cityName}")
            ->line("**" . __('emails.booking.date', [], 'Date') . ":** {$booking->booking_date->format('l, F j, Y')}")
            ->line("**" . __('emails.booking.time_slot', [], 'Time Slot') . ":** {$timeSlot}")
            ->line("**" . __('emails.booking.guests', [], 'Number of Guests') . ":** {$booking->number_of_guests}")
            ->line('---')
            ->line("**{$paymentLabel}:** {$amountPaid} " . __('currency.omr', [], 'OMR'));

        // Show balance due for advance payments
        if ($isAdvance && $booking->balance_due > 0) {
            $balanceDue = number_format((float) $booking->balance_due, 3);
            $mail->line("**" . __('emails.booking.balance_due', [], 'Balance Due') . ":** {$balanceDue} " . __('currency.omr', [], 'OMR'));
            $mail->line(__('emails.booking.balance_note', [], 'Please note: The remaining balance must be paid before the event date.'));
        }

        $mail->line('---');

        // CTA: View booking in customer dashboard
        $mail->action(
            __('emails.booking.view_booking', [], 'View Booking Details'),
            $bookingUrl
        );

        // PDF Attachment note
        $mail->line('📄 ' . __('emails.booking.pdf_attached', [], 'A PDF copy of your booking confirmation is attached to this email.'));

        // Closing
        $mail->salutation(
            __('emails.booking.regards', [], 'Best Regards') . ",\n**" . config('app.name', 'Majalis') . '**'
        );

        // Attach PDF if available
        $this->attachPdf($mail, $booking);

        return $mail;
    }

    /**
     * Attach booking confirmation PDF to the email.
     *
     * Reuses BookingPdfService::generateConfirmation() which saves PDF to storage.
     * If PDF already exists (generated during payment success), attaches it directly.
     * If not, generates a new one on the fly.
     *
     * @param MailMessage $mail
     * @param Booking $booking
     * @return void
     */
    protected function attachPdf(MailMessage $mail, Booking $booking): void
    {
        try {
            // Check if PDF was already generated (invoice_path set during payment success)
            $pdfPath = $booking->invoice_path;

            if (!$pdfPath || !Storage::disk('public')->exists($pdfPath)) {
                // Generate PDF if it doesn't exist yet
                $pdfService = app(BookingPdfService::class);
                $pdfPath = $pdfService->generateConfirmation($booking);
            }

            // Get the full filesystem path for attachment
            $fullPath = Storage::disk('public')->path($pdfPath);

            if (file_exists($fullPath)) {
                $mail->attach($fullPath, [
                    'as' => $booking->booking_number . '.pdf',
                    'mime' => 'application/pdf',
                ]);

                Log::info('PDF attached to confirmation email', [
                    'booking_id' => $booking->id,
                    'pdf_path' => $pdfPath,
                ]);
            } else {
                Log::warning('PDF file not found for email attachment', [
                    'booking_id' => $booking->id,
                    'expected_path' => $fullPath,
                ]);
            }
        } catch (\Exception $e) {
            // PDF attachment is non-critical — send email without it
            Log::warning('Failed to attach PDF to confirmation email (email will still be sent)', [
                'booking_id' => $booking->id,
                'error' => $e->getMessage(),
            ]);
        }
    }

    /**
     * Get localized hall name.
     *
     * Handles both Spatie Translatable (JSON array) and plain string formats.
     *
     * @param Booking $booking
     * @param string $locale
     * @return string
     */
    protected function getHallName(Booking $booking, string $locale): string
    {
        if (!$booking->hall) {
            return 'N/A';
        }

        // Spatie Translatable: name is stored as JSON {"en": "...", "ar": "..."}
        if (method_exists($booking->hall, 'getTranslation')) {
            return $booking->hall->getTranslation('name', $locale)
                ?? $booking->hall->getTranslation('name', 'en')
                ?? 'N/A';
        }

        // Fallback: plain string or array
        $name = $booking->hall->name;
        if (is_array($name)) {
            return $name[$locale] ?? $name['en'] ?? 'N/A';
        }

        return $name ?? 'N/A';
    }

    /**
     * Get localized city name.
     *
     * @param Booking $booking
     * @param string $locale
     * @return string
     */
    protected function getCityName(Booking $booking, string $locale): string
    {
        $city = $booking->hall?->city;

        if (!$city) {
            return '';
        }

        if (method_exists($city, 'getTranslation')) {
            return $city->getTranslation('name', $locale)
                ?? $city->getTranslation('name', 'en')
                ?? '';
        }

        $name = $city->name;
        if (is_array($name)) {
            return $name[$locale] ?? $name['en'] ?? '';
        }

        return $name ?? '';
    }

    /**
     * Get localized time slot label.
     *
     * @param string|null $timeSlot
     * @return string
     */
    protected function getTimeSlotLabel(?string $timeSlot): string
    {
        $labels = [
            'morning' => __('halls.time_slot_morning', [], 'Morning'),
            'afternoon' => __('halls.time_slot_afternoon', [], 'Afternoon'),
            'evening' => __('halls.time_slot_evening', [], 'Evening'),
            'full_day' => __('halls.time_slot_full_day', [], 'Full Day'),
        ];

        return $labels[$timeSlot] ?? ucfirst(str_replace('_', ' ', $timeSlot ?? 'N/A'));
    }

    /**
     * Get the array representation of the notification.
     *
     * Used for database/broadcast channels if enabled later.
     *
     * @param mixed $notifiable
     * @return array<string, mixed>
     */
    public function toArray(mixed $notifiable): array
    {
        return [
            'type' => 'customer_booking_confirmation',
            'booking_id' => $this->booking->id,
            'booking_number' => $this->booking->booking_number,
            'hall_id' => $this->booking->hall_id,
            'total_amount' => $this->booking->total_amount,
            'payment_type' => $this->booking->payment_type,
        ];
    }
}
